# TODO: Add comment
# 
# Author: pcardoso
###############################################################################


## Check drugs
### Table of drug concept list
#test_concept_drugs <- dbGetQueryMap(con, "select * from o_concept_drugs")
#### Example for glibene
#drug_name_example = "ozemp" 
#test_concept_drugs %>% filter(grepl(drug_name_example, drugname, ignore.case = TRUE)) %>% select(drugname) %>% unique() %>% print()
#test_concept_drugs %>% filter(grepl(drug_name_example, drugname, ignore.case = TRUE)) %>% select(drugname, total) %>% unique() %>% group_by(drugname) %>% mutate(total = sum(total)) %>% ungroup() %>% unique()
#test_concept_drugs %>% filter(grepl(drug_name_example, drugname, ignore.case = TRUE)) %>% select(drugname, total, strength) %>% unique() %>% print()


## load libraries
library(tidyverse)

drug_class_table <- data.frame(drugname = "METFORMIN", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = NA, drug_substance_2 = NA) %>%
	rbind(
		## Metformin names
		data.frame(drugname = "METFORMIN HYDROCHLORIDE", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "GLUCOPHAGE SR", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "YALTORMIN SR", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "GLUCOPHAGE", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "SUKKARTO SR", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "METABET SR", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "METFORMIN SR", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "GLUCAMET", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "BOLAMYN SR", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "METFORMIN ORAL PWDR", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "METFORMIN HYDROCHLORIDE SR", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "METSOL", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "METFORMIN SUSTAINED RELEASE", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "METFORMIN SOLUTION X", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "METFORMIN S.R", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "METFORMIN S / R", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "METFORMIN ORAL POWDER", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "METFORMIN ORAL", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "METFORMIN HYDROCLORIDE SR", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "METFORMIN HYDROCHLORIDE S / R", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "METFORMIN HYDROCHLORIDE POWDER FOR", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "METFORMIN HYDROCHLORIDE ORAL POWDER", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "METFORMIN HYDROCHLOR SR", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "METFORMIN HYDROCHLOR", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "METFORMIN F / C", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "METFORMIN ELIXIR", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "METFORMIN 500 MGMS", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "METFORMIN 500", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "MEIJUMET", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "GLUCOREX SR", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "GLUCOPHAGE POWDER FOR", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "GLUCIENT SR", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "GLUCAMET 850", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "GLUCAMET 500", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "DIAGEMET XL", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "JANUMET", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = "DPP4", drug_substance_2 = "Sitagliptin"),
		data.frame(drugname = "METFORMIN AND SITAGLIPTIN", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = "DPP4", drug_substance_2 = "Sitagliptin"),
		data.frame(drugname = "METFORMIN AND ROSIGLITAZONE", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = "TZD", drug_substance_2 = "Rosiglitazone"),
		data.frame(drugname = "METFORMIN WITH ROSIGLITAZONE", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = "TZD", drug_substance_2 = "Rosiglitazone"),
		data.frame(drugname = "METFORMIN + ROSIGLITAZONE", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = "TZD", drug_substance_2 = "Rosiglitazone"),
		data.frame(drugname = "METFORMIN / ROSIGLITAZONE", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = "TZD", drug_substance_2 = "Rosiglitazone"),
		data.frame(drugname = "METFORMIN WITH PIOGLITAZONE", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = "TZD", drug_substance_2 = "Pioglitazone"),
		data.frame(drugname = "METFORMIN + PIOGLITAZONE", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = "TZD", drug_substance_2 = "Pioglitazone"),
		data.frame(drugname = "METFORMIN AND LINAGLIPTIN", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = "DPP4", drug_substance_2 = "Linagliptin"),
		data.frame(drugname = "METFORMIN AND VILDAGLIPTIN", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = "DPP4", drug_substance_2 = "Vildagliptin"),
		data.frame(drugname = "KOMBOGLYZE", drug_class_1 = "MFN", drug_substance_1 = "Metformin", drug_class_2 = "DPP4", drug_substance_2 = "Saxagliptin"),
		## SGLT2i names
		data.frame(drugname = "DAPAGLIFLOZIN", drug_class_1 = "SGLT2", drug_substance_1 = "Dapagliflozin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "DAPAGLIFLOZIN AND METFORMIN", drug_class_1 = "SGLT2", drug_substance_1 = "Dapagliflozin", drug_class_2 = "MFN", drug_substance_2 = "Metformin"),
		data.frame(drugname = "FORXIGA", drug_class_1 = "SGLT2", drug_substance_1 = "Dapagliflozin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "XIGDUO", drug_class_1 = "SGLT2", drug_substance_1 = "Dapagliflozin", drug_class_2 = "MFN", drug_substance_2 = "Metformin"),
		data.frame(drugname = "CANAGLIFLOZIN", drug_class_1 = "SGLT2", drug_substance_1 = "Canagliflozin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "CANAGLIFLOZIN AND METFORMIN", drug_class_1 = "SGLT2", drug_substance_1 = "Canagliflozin", drug_class_2 = "MFN", drug_substance_2 = "Metformin"),
		data.frame(drugname = "INVOKANA", drug_class_1 = "SGLT2", drug_substance_1 = "Canagliflozin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "EMPAGLIFLOZIN", drug_class_1 = "SGLT2", drug_substance_1 = "Empagliflozin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "EMPAGLIFLOZIN AND METFORMIN", drug_class_1 = "SGLT2", drug_substance_1 = "Empagliflozin", drug_class_2 = "MFN", drug_substance_2 = "Metformin"),
		data.frame(drugname = "EMPAGLIFLOZIN AND LINAGLIPTIN", drug_class_1 = "SGLT2", drug_substance_1 = "Empagliflozin", drug_class_2 = "DPP4", drug_substance_2 = "Linagliptin"),
		data.frame(drugname = "JARDIANCE", drug_class_1 = "SGLT2", drug_substance_1 = "Empagliflozin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "VOKANAMET", drug_class_1 = "SGLT2", drug_substance_1 = "Canagliflozin", drug_class_2 = "MFN", drug_substance_2 = "Metformin"),
		data.frame(drugname = "SYNJARDY", drug_class_1 = "SGLT2", drug_substance_1 = "Empagliflozin", drug_class_2 = "MFN", drug_substance_2 = "Metformin"),
		data.frame(drugname = "QTERN", drug_class_1 = "SGLT2", drug_substance_1 = "Dapagliflozin", drug_class_2 = "DPP4", drug_substance_2 = "Saxagliptin"),
		data.frame(drugname = "ERTUGLIFLOZIN", drug_class_1 = "SGLT2", drug_substance_1 = "Ertugliflozin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "STEGLATRO", drug_class_1 = "SGLT2", drug_substance_1 = "Ertugliflozin", drug_class_2 = NA, drug_substance_2 = NA),
		## TZD names
		data.frame(drugname = "ROSIGLITAZONE", drug_class_1 = "TZD", drug_substance_1 = "Rosiglitazone", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "ROSIGLITAZONE MALEATE", drug_class_1 = "TZD", drug_substance_1 = "Rosiglitazone", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "ROSIGLITAZONE AND METFORMIN", drug_class_1 = "TZD", drug_substance_1 = "Rosiglitazone", drug_class_2 = "MFN", drug_substance_2 = "Metformin"),
		data.frame(drugname = "ROSIGLITAZONE + METFORMIN", drug_class_1 = "TZD", drug_substance_1 = "Rosiglitazone", drug_class_2 = "MFN", drug_substance_2 = "Metformin"),
		data.frame(drugname = "ROSIGLITAZONE WITH METFORMIN", drug_class_1 = "TZD", drug_substance_1 = "Rosiglitazone", drug_class_2 = "MFN", drug_substance_2 = "Metformin"),
		data.frame(drugname = "ROSIGLITAZONE F-C", drug_class_1 = "TZD", drug_substance_1 = "Rosiglitazone", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "ROSIGLITAZONE ROSIGLITAZONE", drug_class_1 = "TZD", drug_substance_1 = "Rosiglitazone", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "ROSIGLITAZONE / METFORMIN", drug_class_1 = "TZD", drug_substance_1 = "Rosiglitazone", drug_class_2 = "MFN", drug_substance_2 = "Metformin"),
		data.frame(drugname = "ROSIGLITAZON", drug_class_1 = "TZD", drug_substance_1 = "Rosiglitazone", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "AVANDIA ROSIGLITAZONE", drug_class_1 = "TZD", drug_substance_1 = "Rosiglitazone", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "AVANDIA", drug_class_1 = "TZD", drug_substance_1 = "Rosiglitazone", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "AVANDIA 8", drug_class_1 = "TZD", drug_substance_1 = "Rosiglitazone", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "AVANDIAMET2 / 1", drug_class_1 = "TZD", drug_substance_1 = "Rosiglitazone", drug_class_2 = "MFN", drug_substance_2 = "Metformin"),
		data.frame(drugname = "PIOGLITAZONE", drug_class_1 = "TZD", drug_substance_1 = "Pioglitazone", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "PIOGLITAZONE HYDROCHLORIDE", drug_class_1 = "TZD", drug_substance_1 = "Pioglitazone", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "PIOGLITAZONE AND METFORMIN", drug_class_1 = "TZD", drug_substance_1 = "Pioglitazone", drug_class_2 = "MFN", drug_substance_2 = "Metformin"),
		data.frame(drugname = "PIOGLITAZONE + METFORMIN", drug_class_1 = "TZD", drug_substance_1 = "Pioglitazone", drug_class_2 = "MFN", drug_substance_2 = "Metformin"),
		data.frame(drugname = "PIOGLITAZONE WITH METFORMIN", drug_class_1 = "TZD", drug_substance_1 = "Pioglitazone", drug_class_2 = "MFN", drug_substance_2 = "Metformin"),
		data.frame(drugname = "PIOGLITAZON", drug_class_1 = "TZD", drug_substance_1 = "Pioglitazone", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "PIOGLITAZONE (ACTOS)", drug_class_1 = "TZD", drug_substance_1 = "Pioglitazone", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "ACTOS PIOGLITAZONE", drug_class_1 = "TZD", drug_substance_1 = "Pioglitazone", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "COMPETACT (PIOGLITAZONE / METFORMIN)", drug_class_1 = "TZD", drug_substance_1 = "Pioglitazone", drug_class_2 = "MFN", drug_substance_2 = "Metformin"),
		data.frame(drugname = "ACTOS", drug_class_1 = "TZD", drug_substance_1 = "Pioglitazone", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "GLIZOFAR", drug_class_1 = "TZD", drug_substance_1 = "Pioglitazone", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "GLIDIPION", drug_class_1 = "TZD", drug_substance_1 = "Pioglitazone", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "TROGLITAZONE", drug_class_1 = "TZD", drug_substance_1 = "Troglitazone", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "BIGUANIDE TROGLITAZONE", drug_class_1 = "TZD", drug_substance_1 = "Troglitazone", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "TROGLITAZONE200 MCG", drug_class_1 = "TZD", drug_substance_1 = "Troglitazone", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "TROGLITIAZONE", drug_class_1 = "TZD", drug_substance_1 = "Troglitazone", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "ROMOZIN", drug_class_1 = "TZD", drug_substance_1 = "Troglitazone", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "ROMOZIN (TROGLITAZONE)", drug_class_1 = "TZD", drug_substance_1 = "Troglitazone", drug_class_2 = NA, drug_substance_2 = NA),
		## DPP4i names
		data.frame(drugname = "SITAGLIPTIN", drug_class_1 = "DPP4", drug_substance_1 = "Sitagliptin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "SITAGLIPTIN + METFORMIN", drug_class_1 = "DPP4", drug_substance_1 = "Sitagliptin", drug_class_2 = "MFN", drug_substance_2 = "Metformin"),
		data.frame(drugname = "SITAGLIPTON", drug_class_1 = "DPP4", drug_substance_1 = "Sitagliptin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "SITAGLIPTAIN", drug_class_1 = "DPP4", drug_substance_1 = "Sitagliptin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "SITAGLIPTAN / METFORMIN", drug_class_1 = "DPP4", drug_substance_1 = "Sitagliptin", drug_class_2 = "MFN", drug_substance_2 = "Metformin"),
		data.frame(drugname = "SITAGLEPTIN", drug_class_1 = "DPP4", drug_substance_1 = "Sitagliptin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "SITAGLIPITIN", drug_class_1 = "DPP4", drug_substance_1 = "Sitagliptin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "SITAGLIPTIW", drug_class_1 = "DPP4", drug_substance_1 = "Sitagliptin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "JANUVIA", drug_class_1 = "DPP4", drug_substance_1 = "Sitagliptin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "VILDAGLIPTIN", drug_class_1 = "DPP4", drug_substance_1 = "Vildagliptin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "VILDAGLIPTIN + METFORMIN", drug_class_1 = "DPP4", drug_substance_1 = "Vildagliptin", drug_class_2 = "MFN", drug_substance_2 = "Metformin"),
		data.frame(drugname = "VILDAGLIPTIN / METFORMIN", drug_class_1 = "DPP4", drug_substance_1 = "Vildagliptin", drug_class_2 = "MFN", drug_substance_2 = "Metformin"),
		data.frame(drugname = "VILDAGLIPTIN WITH METFORMIN", drug_class_1 = "DPP4", drug_substance_1 = "Vildagliptin", drug_class_2 = "MFN", drug_substance_2 = "Metformin"),
		data.frame(drugname = "GALVUS", drug_class_1 = "DPP4", drug_substance_1 = "Vildagliptin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "SAXAGLIPTIN", drug_class_1 = "DPP4", drug_substance_1 = "Saxagliptin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "SAXAGLIPTIN AND METFORMIN", drug_class_1 = "DPP4", drug_substance_1 = "Saxagliptin", drug_class_2 = "MFN", drug_substance_2 = "Metformin"),
		data.frame(drugname = "SAXAGLIPTIN AND DAPAGLIFLOZIN", drug_class_1 = "DPP4", drug_substance_1 = "Saxagliptin", drug_class_2 = "SGLT2", drug_substance_2 = "Dapagliflozin"),
		data.frame(drugname = "SAXAGLIPTAN", drug_class_1 = "DPP4", drug_substance_1 = "Saxagliptin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "ONGLYZA", drug_class_1 = "DPP4", drug_substance_1 = "Saxagliptin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "LINAGLIPTIN", drug_class_1 = "DPP4", drug_substance_1 = "Linagliptin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "TRAJENTA", drug_class_1 = "DPP4", drug_substance_1 = "Linagliptin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "JENTADUETO", drug_class_1 = "DPP4", drug_substance_1 = "Linagliptin", drug_class_2 = "MFN", drug_substance_2 = "Metformin"),
		data.frame(drugname = "ALOGLIPTIN", drug_class_1 = "DPP4", drug_substance_1 = "Alogliptin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "ALOGLIPTIN AND METFORMIN", drug_class_1 = "DPP4", drug_substance_1 = "Alogliptin", drug_class_2 = "MFN", drug_substance_2 = "Metformin"),
		data.frame(drugname = "VIPIDIA", drug_class_1 = "DPP4", drug_substance_1 = "Alogliptin", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "VIPDOMET", drug_class_1 = "DPP4", drug_substance_1 = "Alogliptin", drug_class_2 = "MFN", drug_substance_2 = "Metformin"),
		## SU names
		data.frame(drugname = "AMARYL", drug_class_1 = "SU", drug_substance_1 = "Glimepiride", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "CHLORPROPAMIDE", drug_class_1 = "SU", drug_substance_1 = "Chlorpropamide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "DAONIL", drug_class_1 = "SU", drug_substance_1 = "Glibenclamide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "SEMI-DAONIL", drug_class_1 = "SU", drug_substance_1 = "Glibenclamide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "SEMI DAONIL", drug_class_1 = "SU", drug_substance_1 = "Glibenclamide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "SEMI / DAONIL", drug_class_1 = "SU", drug_substance_1 = "Glibenclamide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "DIABETAMIDE", drug_class_1 = "SU", drug_substance_1 = "Glibenclamide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "DIAMICRON", drug_class_1 = "SU", drug_substance_1 = "Gliclazide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "DIAMICRON SR", drug_class_1 = "SU", drug_substance_1 = "Gliclazide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "DIAMICRON DIAMICRON", drug_class_1 = "SU", drug_substance_1 = "Gliclazide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "DIAMICRON 80 MGM", drug_class_1 = "SU", drug_substance_1 = "Gliclazide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "DIAMICRONE", drug_class_1 = "SU", drug_substance_1 = "Gliclazide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "EUGLUCON", drug_class_1 = "SU", drug_substance_1 = "Glibenclamide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "GLIBENCLAMIDE", drug_class_1 = "SU", drug_substance_1 = "Glibenclamide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "GLIBENESE", drug_class_1 = "SU", drug_substance_1 = "Glipizide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "GLIPIZIDE", drug_class_1 = "SU", drug_substance_1 = "Glipizide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "GLIPIZIDE PP", drug_class_1 = "SU", drug_substance_1 = "Glipizide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "GLIMEPIRIDE", drug_class_1 = "SU", drug_substance_1 = "Glimepiride", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "GLICLAZIDE", drug_class_1 = "SU", drug_substance_1 = "Gliclazide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "<<D>>GLICLAZIDE", drug_class_1 = "SU", drug_substance_1 = "Gliclazide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "GLICLAZIDE 40", drug_class_1 = "SU", drug_substance_1 = "Gliclazide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "GLICLAZIDE 1", drug_class_1 = "SU", drug_substance_1 = "Gliclazide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "GLICLAZIDE SR", drug_class_1 = "SU", drug_substance_1 = "Gliclazide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "GLICLAZIDE STUDY PREP", drug_class_1 = "SU", drug_substance_1 = "Gliclazide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "GLICLAZIDE XL", drug_class_1 = "SU", drug_substance_1 = "Gliclazide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "GLURENORM", drug_class_1 = "SU", drug_substance_1 = "Gliquidone", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "GLIQUIDONE", drug_class_1 = "SU", drug_substance_1 = "Gliquidone", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "MINODIAB", drug_class_1 = "SU", drug_substance_1 = "Glipizide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "TOLBUTAMIDE", drug_class_1 = "SU", drug_substance_1 = "Tolbutamide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "DIAGLYK", drug_class_1 = "SU", drug_substance_1 = "Gliclazide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "DIAGLYCK", drug_class_1 = "SU", drug_substance_1 = "Gliclazide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "DIAGLY K", drug_class_1 = "SU", drug_substance_1 = "Gliclazide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "DIAGLYX", drug_class_1 = "SU", drug_substance_1 = "Gliclazide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "NAZDOL", drug_class_1 = "SU", drug_substance_1 = "Gliclazide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "DACADIS", drug_class_1 = "SU", drug_substance_1 = "Gliclazide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "ZICRON", drug_class_1 = "SU", drug_substance_1 = "Gliclazide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "ZICRON PR", drug_class_1 = "SU", drug_substance_1 = "Gliclazide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "EDICIL", drug_class_1 = "SU", drug_substance_1 = "Gliclazide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "LAAGLYDA", drug_class_1 = "SU", drug_substance_1 = "Gliclazide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "VAMJU", drug_class_1 = "SU", drug_substance_1 = "Gliclazide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "BILXONA", drug_class_1 = "SU", drug_substance_1 = "Gliclazide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "TOLAZAMIDE", drug_class_1 = "SU", drug_substance_1 = "Tolazamide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "DIABINESE", drug_class_1 = "SU", drug_substance_1 = "Chlorpropamide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "DIAMICROM", drug_class_1 = "SU", drug_substance_1 = "Gliclazide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "RASTINON", drug_class_1 = "SU", drug_substance_1 = "Tolbutamide", drug_class_2 = NA, drug_substance_2 = NA),
		## GLP1 names
		data.frame(drugname = "LIRAGLUTIDE", drug_class_1 = "GLP1", drug_substance_1 = "Liraglutide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "LIRAGLUTIDE INJECTION", drug_class_1 = "GLP1", drug_substance_1 = "Liraglutide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "INSULIN DEGLUDEC 100 UNITS / ML / LIRAGLUTIDE", drug_class_1 = "GLP1", drug_substance_1 = "Liraglutide", drug_class_2 = "INS", drug_substance_2 = "Insulin"),
		data.frame(drugname = "LIRAGLUTIDE PREFILLED", drug_class_1 = "GLP1", drug_substance_1 = "Liraglutide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "INSULIN DEGLUDEC AND LIRAGLUTIDE", drug_class_1 = "GLP1", drug_substance_1 = "Liraglutide", drug_class_2 = "INS", drug_substance_2 = "Insulin"),
		data.frame(drugname = "LIRAGLUTIDE 1", drug_class_1 = "GLP1", drug_substance_1 = "Liraglutide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "LIRAGLUTIDE PRE FILLED", drug_class_1 = "GLP1", drug_substance_1 = "Liraglutide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "LIRAGLUTIDE PREFILLED PENS", drug_class_1 = "GLP1", drug_substance_1 = "Liraglutide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "VICTOZA", drug_class_1 = "GLP1", drug_substance_1 = "Liraglutide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "VICTOZA INJECTION", drug_class_1 = "GLP1", drug_substance_1 = "Liraglutide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "VICTOZA PREFILLED", drug_class_1 = "GLP1", drug_substance_1 = "Liraglutide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "VICTOZA PREFILLED PENS", drug_class_1 = "GLP1", drug_substance_1 = "Liraglutide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "LIXISENATIDE", drug_class_1 = "GLP1", drug_substance_1 = "Lixisenatide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "INSULIN GLARGINE 100 UNITS / ML / LIXISENATIDE", drug_class_1 = "GLP1", drug_substance_1 = "Lixisenatide", drug_class_2 = "INS", drug_substance_2 = "Insulin"),
		data.frame(drugname = "LYXUMIA", drug_class_1 = "GLP1", drug_substance_1 = "Lixisenatide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "XULTOPHY 100 UNITS", drug_class_1 = "GLP1", drug_substance_1 = "Liraglutide", drug_class_2 = "INS", drug_substance_2 = "Insulin"),
		data.frame(drugname = "XULTOPHY", drug_class_1 = "GLP1", drug_substance_1 = "Liraglutide", drug_class_2 = "INS", drug_substance_2 = "Insulin"),
		data.frame(drugname = "DULAGLUTIDE", drug_class_1 = "GLP1", drug_substance_1 = "Dulaglutide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "TRULICITY", drug_class_1 = "GLP1", drug_substance_1 = "Dulaglutide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "ALBIGLUTIDE", drug_class_1 = "GLP1", drug_substance_1 = "Albiglutide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "SAXENDA", drug_class_1 = "GLP1", drug_substance_1 = "Liraglutide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "EXENATIDE", drug_class_1 = "GLP1", drug_substance_1 = "Exenatide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "EXENATIDE INJECTION", drug_class_1 = "GLP1", drug_substance_1 = "Exenatide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "EXENATIDE 60 DOSE PREFILLED", drug_class_1 = "GLP1", drug_substance_1 = "Exenatide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "EXENATIDE POWDER AND SOLVENT FOR", drug_class_1 = "GLP1", drug_substance_1 = "Exenatide prolonged-release", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "EXENATIDE 60-DOSE PREFILLED", drug_class_1 = "GLP1", drug_substance_1 = "Exenatide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "EXENATIDE PWDR FOR INJECTIONSUSP", drug_class_1 = "GLP1", drug_substance_1 = "Exenatide prolonged-release", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "EXENATIDE SINGLE PREFILLED", drug_class_1 = "GLP1", drug_substance_1 = "Exenatide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "BYETTA (EXENATIDE)", drug_class_1 = "GLP1", drug_substance_1 = "Exenatide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "EXENATIDE INJECTION PREFILLED", drug_class_1 = "GLP1", drug_substance_1 = "Exenatide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "EXENATIDE PREFILLED", drug_class_1 = "GLP1", drug_substance_1 = "Exenatide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "EXENATIDE PRE FILLED", drug_class_1 = "GLP1", drug_substance_1 = "Exenatide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "EXENATIDE(BYETTA)", drug_class_1 = "GLP1", drug_substance_1 = "Exenatide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "EXENATIDE DISPOSABLE PENS", drug_class_1 = "GLP1", drug_substance_1 = "Exenatide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "EXENATIDE EXENATIDE", drug_class_1 = "GLP1", drug_substance_1 = "Exenatide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "EXENATIDE PREFILLED PENS", drug_class_1 = "GLP1", drug_substance_1 = "Exenatide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "BYETTA EXENATIDE", drug_class_1 = "GLP1", drug_substance_1 = "Exenatide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "EXENATIDE DISPOSABLE", drug_class_1 = "GLP1", drug_substance_1 = "Exenatide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "EXENATIDE SUBCUTANEOUS", drug_class_1 = "GLP1", drug_substance_1 = "Exenatide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "BYETTA", drug_class_1 = "GLP1", drug_substance_1 = "Exenatide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "BYETTA INJECTION", drug_class_1 = "GLP1", drug_substance_1 = "Exenatide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "BYETTA 60 DOSE PREFILLED", drug_class_1 = "GLP1", drug_substance_1 = "Exenatide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "BYETTA PREFILLED", drug_class_1 = "GLP1", drug_substance_1 = "Exenatide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "BYETTA BYETTA 10 UG PREFILLED", drug_class_1 = "GLP1", drug_substance_1 = "Exenatide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "BYETTA INSULIN", drug_class_1 = "GLP1", drug_substance_1 = "Exenatide", drug_class_2 = "INS", drug_substance_2 = "Insulin"),
		data.frame(drugname = "BYETTA 10", drug_class_1 = "GLP1", drug_substance_1 = "Exenatide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "BYETTA BYETTA 5 UG PREFILLED", drug_class_1 = "GLP1", drug_substance_1 = "Exenatide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "BYETTA PENS", drug_class_1 = "GLP1", drug_substance_1 = "Exenatide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "BYETTA INJECTION 10 UG PENFILLED", drug_class_1 = "GLP1", drug_substance_1 = "Exenatide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "BYETTA PREFILLED DISPOSABLE", drug_class_1 = "GLP1", drug_substance_1 = "Exenatide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "BYETTA PREFILLED INJECTION", drug_class_1 = "GLP1", drug_substance_1 = "Exenatide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "BYETTA PENS BYETTA", drug_class_1 = "GLP1", drug_substance_1 = "Exenatide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "BYDUREON", drug_class_1 = "GLP1", drug_substance_1 = "Exenatide prolonged-release", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "BYDUREON BCISE", drug_class_1 = "GLP1", drug_substance_1 = "Exenatide prolonged-release", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "BYDUREON PWDR FOR INJECTIONSUSP", drug_class_1 = "GLP1", drug_substance_1 = "Exenatide prolonged-release", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "BYDUREON POWDER AND SOLVENT FOR", drug_class_1 = "GLP1", drug_substance_1 = "Exenatide prolonged-release", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "OZEMPIC", drug_class_1 = "GLP1", drug_substance_1 = "Low-dose semaglutide", drug_class_2 = NA, drug_substance_2 = NA),
		data.frame(drugname = "RYBELSUS", drug_class_1 = "GLP1", drug_substance_1 = "Oral semaglutide", drug_class_2 = NA, drug_substance_2 = NA)
	)
		
## Check if any entries are duplicated
drug_class_table %>% select(drugname) %>% unique() %>% nrow()
drug_class_table %>% nrow()

	
saveRDS(drug_class_table, "/home/pcardoso/workspace/SDRN-Cohort-scripts/Codelists/Diabetes Medication/data_class_table.rds")
